#include <lazytmux/cmdmode/commands.hpp>

#include <array>
#include <span>
#include <string_view>

namespace lazytmux::cmdmode {

namespace {

inline constexpr std::array<std::string_view, 95> kCommandsArr{
    "attach",
    "attach-session",
    "bind-key",
    "break-pane",
    "capture-pane",
    "choose-buffer",
    "choose-client",
    "choose-tree",
    "clear-history",
    "clock-mode",
    "command-prompt",
    "confirm-before",
    "copy-mode",
    "delete-buffer",
    "detach",
    "detach-client",
    "display-menu",
    "display-message",
    "display-panes",
    "display-popup",
    "find-window",
    "has-session",
    "if-shell",
    "join-pane",
    "kill-pane",
    "kill-server",
    "kill-session",
    "kill-window",
    "last-pane",
    "last-window",
    "link-window",
    "list-buffers",
    "list-clients",
    "list-commands",
    "list-keys",
    "list-panes",
    "list-sessions",
    "list-windows",
    "load-buffer",
    "lock-client",
    "lock-server",
    "lock-session",
    "ls",
    "lsk",
    "lsp",
    "lsw",
    "menu",
    "move-pane",
    "move-window",
    "new",
    "new-session",
    "new-window",
    "next-layout",
    "next-window",
    "paste-buffer",
    "pipe-pane",
    "previous-layout",
    "previous-window",
    "refresh-client",
    "rename-session",
    "rename-window",
    "resize-pane",
    "resize-window",
    "respawn-pane",
    "respawn-window",
    "rotate-window",
    "run-shell",
    "save-buffer",
    "select-layout",
    "select-pane",
    "select-window",
    "send-keys",
    "send-prefix",
    "set-buffer",
    "set-environment",
    "set-hook",
    "set-option",
    "set-window-option",
    "show-buffer",
    "show-environment",
    "show-hooks",
    "show-messages",
    "show-options",
    "show-window-options",
    "source",
    "source-file",
    "split-window",
    "start-server",
    "suspend-client",
    "swap-pane",
    "swap-window",
    "switch-client",
    "unbind-key",
    "unlink-window",
    "wait-for",
};

}  // namespace

const std::span<const std::string_view> kCommands{kCommandsArr};

}  // namespace lazytmux::cmdmode
